### ISSUE TITLE
Feature: Backdrop CMS Resources (helpful links)

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/dashboard_plus#10]
For the first block, I created a simple hardcoded list of links to helpful Backdrop CMS resources. For now, I've included the following links, open to ideas:

* Ask A Question - Backdrop CMS Forums
* Learn about Backdrop CMS - User Guide
* Report a bug - Backdrop CMS Core Issue Queue

![Dashboard___starter](https://user-images.githubusercontent.com/3144571/60144390-ce5b9b80-9787-11e9-9c4c-67fda87d6730.png)

**Comment by docwilmot** [comment]
Instead of:
```
$block['subject'] = 'Backdrop CMS Resources';
  $block['content'] = $block['content'] . '<li><a target="_blank" href="https://forum.backdropcms.org">Ask A Question</a> - Backdrop CMS Forums</li>';
  $block['content'] = $block['content'] . '<li><a target="_blank" href="https://backdropcms.org/user-
...
```
 you could do 
```
$block['subject'] = 'Backdrop CMS Resources';
  $block['content'] .=  '<li><a target="_blank" href="https://forum.backdropcms.org">Ask A Question</a> - Backdrop CMS Forums</li>';
  $block['content'] .= '<li><a target="_blank" href="https://backdropcms.org/user-
...
```
etc

**Comment by stpaultim** [comment]
Thanks @docwilmot - I knew that was not the best way, but I forget the best syntax. Was planning on asking someone to review this for me. I like your suggestion and will make this change.

**Comment by stpaultim** [comment]
This appears to be complete.
